custom_admin_toolbar.settings:
  type: config_object
  label: 'Custom admin toolbar settings'
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
    menu_source:
      type: string
      label: 'Menu source'
    hide_user:
      type: boolean
      label: 'Hide user'
    hide_home:
      type: boolean
      label: 'Hide home'